MESYS_STATS = {
        'input_count': {'label': 'Number of vehicles entering the simulation', 'units': 'count'},
        'travel': {'label': 'Total distance traveled', 'units': 'km'},
        'totalWaitingTime': {'label': 'Total time experienced by the vehicles still waiting outside', 'units': 'hours'},
        'totalTravelTimeInside': {'label': 'Total time experienced by the vehicles inside the network', 'units': 'hours'},
        'speed': {'label': 'Mean speed', 'units': 'km/h'},
        'vIn': {'label': 'Number of vehicles inside the network', 'units': 'count'},
        'vOut': {'label': 'Number of vehicles that have exited the network', 'units': 'count'},
        'input_flow': {'label': 'Mean flow in the network', 'units': 'veh/h'},
        'dtime': {'label': 'Mean delay time', 'units': 'sec/km'},
        'density': {'label': 'Density ', 'units': 'veh/km per lane'},
        'vWait': {'label': 'Number of vehicles waiting to enter into the system', 'units': 'count'},
        'vLostIn': {'label': 'Number of vehicles lost in the network', 'units': 'count'},
        'vLostOut': {'label': 'Number of vehicles lost that have exited the network', 'units': 'count'},
        'ttime': {'label': 'Mean travel time', 'units': 'secs'},
        'dtime': {'label': 'Mean delay time', 'units': 'secs'},
        'flow': {'label': 'Mean flow', 'units': 'veh/h'},
        'qmean': {'label': 'Mean Queue Length by lane', 'units': 'veh'},
        'traveltime': {'label': 'Total travel time experienced', 'units': 'hours'},
        'lane_changes': {'label': 'Number of lane changes / Number of veh', 'units': 'count'},
        'total_lane_changes': {'label': 'Number of lane changes', 'units': 'count'},  
        }

MESECT_STATS = {
        'input_count': {'label': 'Number of vehicles entering the simulation', 'units': 'count'},
        'travel': {'label': 'Total distance traveled', 'units': 'km'},
        'speed': {'label': 'Mean speed', 'units': 'km/h'},
        'spdh': {'label': 'Harmonic mean speed', 'units': 'km/h'},
        'dtime': {'label': 'Mean delay time', 'units': 'sec/km'},
        'density': {'label': 'Density ', 'units': 'veh/km per lane'},
        'ttime': {'label': 'Mean travel time', 'units': 'secs'},
        'dtime': {'label': 'Mean delay time', 'units': 'secs'},
        'flow': {'label': 'Mean flow', 'units': 'veh/h'},
        'count': {'label': 'Number of vehicles', 'units': 'count'},
        'flow_capacity': {'label': 'Flow/Section Capacity', 'units': '%'},
        'qmean': {'label': 'Mean Queue Length by lane', 'units': 'veh'},
        'traveltime': {'label': 'Total travel time experienced in the section', 'units': 'secs'},
        'lane_changes': {'label': 'Number of lane changes / Number of veh', 'units': 'count'},
        'total_lane_changes': {'label': 'Number of lane changes', 'units': 'count'},  
        }

